### ISSUE TITLE
Portability and hsmci.c #include statement

### ISSUE THREAD

**Issue by dcnewman** [dc42/CoreDuet#1]
system/libsam/source/hsmci.c has two portability issues in the #include statement,
# include "....\libraries\storage\conf_sd_mmc.h"

The "storage" should be "Storage" for operating systems with case sensitive file systems.  (This because the actual directory is named "Storage".)  Second, forward slashes should probably be used to increase portability.

**Comment by dc42** [comment]
Thanks. I had already picked up the backslashes but not the lower case S. Will be fixed in next commit.
